app = "bot-factory-rwmfna"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python factory_bot.py"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
